.TH find_inside 1
.SH NAME
find_inside \- search a pattern
.SH SYNOPSis
.B find_inside <Dir>|<File> <Pattern>
.SH DESCRIPTION
.B Find_inside 
search a pattern
.B Pattern
since directory
.B Dir
in all files and return the path to that file(s). If first argument is a
regular file return the path to 
.B File
.SH SEE ALSO
.B	find (1)
.SH AUTHOR
.B	Luis Ernesto Gonzales Cardenas (lgcardenas@uclv.edu.cu)
